changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
        - feat
    - title: Fixes 🐛
      labels:
        - bug
        - fix
    - title: Other Changes
      labels:
        - "*"
